[package]
name = "skantravels"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
refinery = { version = "0.8.14", features = ["rusqlite"] }
rusqlite = { version = "0.31", features = ["bundled"] }

